In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.decomposition import TruncatedSVD
import random
# import seaborn as sns
import os.path as path
import os
import matplotlib
import matplotlib.font_manager
import matplotlib.pyplot as plt # graphs plotting
from Bio import SeqIO # some BioPython that will come in handy
#matplotlib inline
import numpy
import csv 

from matplotlib import rc

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import svm

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import classification_report, confusion_matrix 

from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

from pandas import DataFrame

from sklearn.model_selection import KFold 
from sklearn.model_selection import RepeatedKFold

from sklearn.metrics import confusion_matrix

from numpy import mean


from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score

import statistics


# for Arial typefont
matplotlib.rcParams['font.family'] = 'Arial'


## for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
# matplotlib.rcParams['mathtext.fontset'] = 'cm'

## for LaTeX typefont
# matplotlib.rcParams['mathtext.fontset'] = 'stix'
# matplotlib.rcParams['font.family'] = 'STIXGeneral'

## for another LaTeX typefont
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})

# rc('text', usetex = True)

print("Packages imported")

Packages imported


In [2]:
# Original DNA Sequences
# path = "E:/RA/Adversarial Attack/PacBio Dataset/"
path = "E:/RA/Adversarial Attack/PacBio Dataset/NovaSeq_error_files/"


file_name = "illumina_5000_novaseq_simulated_error"
input_file_name = path + file_name + ".fasta"

sequences_dictionary = {sequence.id : sequence.seq for sequence in SeqIO.parse(input_file_name,'fasta')}

print("Data Loaded")

Data Loaded


In [3]:
deflines = [entry for entry in sequences_dictionary.keys()]             # create a list of deflines
protein_sequences = [entry for entry in sequences_dictionary.values()]  # create a list of protein sequences 

In [4]:
sequences_dictionary

{'NC_045512.2': Seq('ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGT...AAA')}

In [13]:
lines = []
with open(path +  'illumina_10000_novaseq_simulated_error.txt') as f:
    lines = f.readlines()

In [14]:
asd = str(lines).replace("\n',","")

In [86]:
# lines

In [87]:
# asd1 = asd.replace("\\n","")

In [15]:

asd1 = asd.replace("\\n","")
asd2 = asd1.replace(", ","")
asd3 = asd2.replace("[","")

asd3[0:1000]

"'>NC_045512.2 ''ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCT''GTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACT''CACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATC''TTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTT''TGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAAC''ACACGTCCAACTCAGTTTGCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGG''AGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGG''CTTAGTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCATCAA''ACGTTCGGGTGCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGGTAGCAGAACT''CGAAGGCATTCAGTACGGTCGTAGTGGTGAGACACTTGGTGTCCTTGTCCCTCATGTGGG''CGAAATACCAGTGGCTTACCGCAAGGTTCTTCTTCGTAAGAACGGTAATAAAGGAGCTGG''TGGCCATAGTTACGGCGCCGATCTAAAGTCATTTGACTTAGGCGACGAGCTTGGCACTGA''TCCTTATGAAGATTTTCAAGAAAACTGGAACACTAAACATAGCAGTGGTGTTACCCGTGA''ACTCATGCGTGAGCTTAACGGAGGGGCATACACTCGCTATGTCGATAACAACTTCTGTGG''CCCTGATGGCTACCCTCTTGAGTGCATTAAAGACCTTCTAGCACGTGCTGGTAAAGCTTC''ATGCACTTTGTCCGAACAACTGGACTTTATTGACACTAAGAGGGGTGTATACT

In [16]:
asd4 = asd3.split(">NC_045512.2 ''")

In [17]:
(asd4[2])

"ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCT''GTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACT''CACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATC''TTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTT''TGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAAC''ACACGTCCAACTCAGTTTGCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGG''AGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGG''CTTAGTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCATCAA''ACGTTCGGATGCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGGTAGCAGAACT''CGAAGGCATTCAGTACGGTCGTAGTGGTGAGACACTTGGTGTCCTTGTCCCTCATGTGGG''CGAAATACCAGTGGCTTACCGCAAGGTTCTTCTTCGTAAGAACGGTAATAAAGGAGCTGG''TGGCCATAGTTACGGCGCCGATCTAAAGTCATTTGACTTAGGCGACGAGCTTGGCACTGA''TCCTTATGAAGATTTTCAAGAAAACTGGAACACTAAACATAGCAGTGGTGTTACCCGTGA''ACTCATGCGTGAGCTTAACGGAGGGGCATACACTCGCTATGTCGATAACAACTTCTGTGG''CCCTGATGGCTACCCTCTTGAGTGCATTAAAGACCTTCTAGCACGTGCTGGTAAAGCTTC''ATGCACTTTGTCCGAACAACTGGACTTTATTGACACTAAGAGGGGTGTATACTGCTGCCG''TGAACAT

In [18]:
len(asd4)

8507

In [19]:
depth = []

for i in range(1,8507):
    asd5 = asd4[i].replace("\'","")
    depth.append(asd5)

In [20]:
np.save(path + "illumina_10000_novaseq_simulated_error.npy",depth)

# Original Data

In [126]:
# Original DNA Sequences
path = "E:/RA/Adversarial Attack/PacBio Dataset/"

file_name = "gisaid_hcov-19"
input_file_name = path + file_name + ".fasta"

sequences_dictionary = {sequence.id : sequence.seq for sequence in SeqIO.parse(input_file_name,'fasta')}

print("Data Loaded")

Data Loaded


In [127]:
deflines = [entry for entry in sequences_dictionary.keys()]             # create a list of deflines
protein_sequences = [entry for entry in sequences_dictionary.values()]  # create a list of protein sequences 

In [151]:
protein_sequences[0]

Seq('TCGTCCGTTTTGCAGCCGATCATCAGCACATCTAGGTTTTGTCCGGGTGTGACC...ATC')

In [133]:
accession_ids = []

for i in range(len(deflines)):
    accession_ids.append(str(deflines[i]).split("|")[1])

In [164]:
accession_ids_df = pd.DataFrame(accession_ids)
accession_ids_df.columns = ["old_ID"]
accession_ids_df

old_ID
0     EPI_ISL_7830814
1     EPI_ISL_7830815
2     EPI_ISL_7830817
3     EPI_ISL_7830818
4     EPI_ISL_7830819
...               ...
8501  EPI_ISL_8130183
8502  EPI_ISL_8130184
8503  EPI_ISL_8130187
8504  EPI_ISL_8130189
8505  EPI_ISL_8130191

[8506 rows x 1 columns]

In [136]:
new_attr = np.load("E:/RA/Adversarial Attack/Dataset/gisaid_hcov_19_orig_8505_attributes.npy")

In [137]:
new_attr[0]

array(['EPI_ISL_7958039', 'AY.122', 'betacoronavirus', 'Human', 'hCoV-19',
       'USA', 'NM-UNM-ED00601', '2021', '2021-12-14'], dtype='<U30')

In [153]:
accession_ids_new = []

for i in range(len(new_attr)):
    asd = new_attr[i]
    accession_ids_new.append(asd[0])

In [158]:
len(accession_ids_new)

8505

In [209]:
new_df_final = pd.DataFrame(accession_ids_new)

In [217]:
data_frame_check = pd.DataFrame(new_attr)
data_frame_check.columns = ["id1","variant","corona","host","year1","country","unq","year2","date"]

In [218]:
data_frame_check

id1 variant           corona   host    year1 country  \
0     EPI_ISL_7958039  AY.122  betacoronavirus  Human  hCoV-19     USA   
1     EPI_ISL_7887172   AY.44  betacoronavirus  Human  hCoV-19     USA   
2     EPI_ISL_7887168  AY.118  betacoronavirus  Human  hCoV-19     USA   
3     EPI_ISL_7897889    AY.3  betacoronavirus  Human  hCoV-19     USA   
4     EPI_ISL_7897886   AY.25  betacoronavirus  Human  hCoV-19     USA   
...               ...     ...              ...    ...      ...     ...   
8500  EPI_ISL_8058751   AY.44  betacoronavirus  Human  hCoV-19     USA   
8501  EPI_ISL_8058754   AY.25  betacoronavirus  Human  hCoV-19     USA   
8502  EPI_ISL_8058771  AY.103  betacoronavirus  Human  hCoV-19     USA   
8503  EPI_ISL_8058782  AY.117  betacoronavirus  Human  hCoV-19     USA   
8504  EPI_ISL_7901532   AY.44  betacoronavirus  Human  hCoV-19     USA   

                         unq year2        date  
0             NM-UNM-ED00601  2021  2021-12-14  
1     NC-CLT-CORVASEQ-003887  2021  2021-12-11  
2     NC-CLT-CORVASEQ-003882  2021  2021-12-11  
3            NE-NCOV21-44851  2021  2021-12-14  
4            NE-NCOV21-44863  2021  2021-12-14  
...                      ...   ...         ...  
8500    WA-CDC-UW21121315199  2021  2021-12-13  
8501    WA-CDC-UW21121363259  2021  2021-12-13  
8502    WA-CDC-UW21121320897  2021  2021-12-13  
8503    WA-CDC-UW21121290272  2021  2021-12-12  
8504            KS-KHEL-8127  2021  2021-12-16  

[8505 rows x 9 columns]

In [155]:

# orig_seq = np.load("E:/RA/Adversarial Attack/Dataset/gisaid_hcov_19_orig_8505_seq.npy",allow_pickle=True)
orig_seq = org_seq_new[:]
depth_5_seq = np.load("E:/RA/Adversarial Attack/Dataset/pacbio_depth_5_simulated_error.npy",allow_pickle=True)
depth_10_seq = np.load("E:/RA/Adversarial Attack/Dataset/pacbio_depth_10_simulated_error.npy",allow_pickle=True)
depth_15_seq = np.load("E:/RA/Adversarial Attack/Dataset/pacbio_depth_15_simulated_error.npy",allow_pickle=True)
depth_20_seq = np.load("E:/RA/Adversarial Attack/Dataset/pacbio_depth_20_simulated_error.npy",allow_pickle=True)
depth_25_seq = np.load("E:/RA/Adversarial Attack/Dataset/pacbio_depth_25_simulated_error.npy",allow_pickle=True)
depth_30_seq = np.load("E:/RA/Adversarial Attack/Dataset/pacbio_depth_30_simulated_error.npy",allow_pickle=True)
depth_35_seq = np.load("E:/RA/Adversarial Attack/Dataset/pacbio_depth_35_simulated_error.npy",allow_pickle=True)



In [200]:
len(depth_35_seq)

8506

In [203]:
new_df = pd.DataFrame(accession_ids_df)
new_df.columns = ["old_ID"]

In [204]:
new_df

old_ID
0     EPI_ISL_7830814
1     EPI_ISL_7830815
2     EPI_ISL_7830817
3     EPI_ISL_7830818
4     EPI_ISL_7830819
...               ...
8501  EPI_ISL_8130183
8502  EPI_ISL_8130184
8503  EPI_ISL_8130187
8504  EPI_ISL_8130189
8505  EPI_ISL_8130191

[8506 rows x 1 columns]

In [197]:
orig_seq_new = []

for i in range(len(orig_seq)):
    orig_seq_new.append(np.array(orig_seq[i]))

In [205]:
len(depth_5_seq)

8506

In [206]:
new_df["org"] = pd.DataFrame(protein_sequences)
new_df["depth_5"] = pd.DataFrame(depth_5_seq)
new_df["depth_10"] = pd.DataFrame(depth_10_seq)
new_df["depth_15"] = pd.DataFrame(depth_15_seq)
new_df["depth_20"] = pd.DataFrame(depth_20_seq)
new_df["depth_25"] = pd.DataFrame(depth_25_seq)
new_df["depth_30"] = pd.DataFrame(depth_30_seq)
new_df["depth_35"] = pd.DataFrame(depth_35_seq)

In [207]:
new_df

old_ID                                                org  \
0     EPI_ISL_7830814  (T, C, G, T, C, C, G, T, T, T, T, G, C, A, G, ...   
1     EPI_ISL_7830815  (T, C, A, T, C, C, G, T, T, T, T, G, C, A, G, ...   
2     EPI_ISL_7830817  (T, C, G, T, C, C, G, T, T, T, T, G, C, A, G, ...   
3     EPI_ISL_7830818  (T, C, G, T, C, C, G, T, T, T, T, G, C, A, G, ...   
4     EPI_ISL_7830819  (T, C, G, T, C, C, G, T, T, T, T, G, C, A, G, ...   
...               ...                                                ...   
8501  EPI_ISL_8130183  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   
8502  EPI_ISL_8130184  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   
8503  EPI_ISL_8130187  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   
8504  EPI_ISL_8130189  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   
8505  EPI_ISL_8130191  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   

                                                depth_5  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
4     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
...                                                 ...   
8501  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8502  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8503  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8504  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8505  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   

                                               depth_10  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
4     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
...                                                 ...   
8501  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8502  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8503  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8504  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8505  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   

                                               depth_15  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
4     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
...                                                 ...   
8501  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8502  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8503  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8504  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8505  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   

                                               depth_20  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
4     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
...                                                 ...   
8501  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8502  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8503  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8504  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8505  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   

                                               depth_25  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGG

In [220]:
final_merged_data = pd.merge(new_df, data_frame_check, left_on='old_ID', right_on='id1', how='left').drop('id1', axis=1)

In [222]:
final_merged_data_without_na = final_merged_data.dropna()

In [223]:
final_merged_data_without_na

old_ID                                                org  \
0     EPI_ISL_7830814  (T, C, G, T, C, C, G, T, T, T, T, G, C, A, G, ...   
1     EPI_ISL_7830815  (T, C, A, T, C, C, G, T, T, T, T, G, C, A, G, ...   
2     EPI_ISL_7830817  (T, C, G, T, C, C, G, T, T, T, T, G, C, A, G, ...   
3     EPI_ISL_7830818  (T, C, G, T, C, C, G, T, T, T, T, G, C, A, G, ...   
4     EPI_ISL_7830819  (T, C, G, T, C, C, G, T, T, T, T, G, C, A, G, ...   
...               ...                                                ...   
8501  EPI_ISL_8130183  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   
8502  EPI_ISL_8130184  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   
8503  EPI_ISL_8130187  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   
8504  EPI_ISL_8130189  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   
8505  EPI_ISL_8130191  (T, C, G, A, T, C, T, C, T, T, G, T, A, G, A, ...   

                                                depth_5  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
4     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
...                                                 ...   
8501  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8502  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8503  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8504  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8505  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   

                                               depth_10  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
4     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
...                                                 ...   
8501  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8502  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8503  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8504  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8505  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   

                                               depth_15  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
4     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
...                                                 ...   
8501  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8502  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8503  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8504  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8505  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   

                                               depth_20  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
4     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
...                                                 ...   
8501  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8502  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8503  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8504  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
8505  ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   

                                               depth_25  \
0     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
1     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
2     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...   
3     ATTAAAGGTTTATACCTTCCCAGG

In [256]:
asdd = final_merged_data_without_na.drop(['org', 'depth_5', 'depth_10', 'depth_15', 'depth_20', 'depth_25', 'depth_30', 'depth_35'], axis=1)

In [257]:
asdd1 = np.array(asdd)

In [259]:
asdd1[0]

array(['EPI_ISL_7830814', 'AY.3', 'betacoronavirus', 'Human', 'hCoV-19',
       'USA', 'WA-CDC-UW21121108607', '2021', '2021-12-11'], dtype=object)

In [260]:
np.save("E:/RA/Adversarial Attack/Dataset/Final_preprocessed/gisaid_hcov_19_org_8505_attributes.npy",asdd1)

In [22]:
# In[4]
def roc_auc_score_multiclass(actual_class, pred_class, average = "macro"):

    unique_class = set(actual_class)
    roc_auc_dict = {}
    for per_class in unique_class:
        #creating a list of all the classes except the current class 
        other_class = [x for x in unique_class if x != per_class]

        #marking the current class as 1 and all other classes as 0
        new_actual_class = [0 if x in other_class else 1 for x in actual_class]
        new_pred_class = [0 if x in other_class else 1 for x in pred_class]

        #using the sklearn metrics method to calculate the roc_auc_score
        roc_auc = roc_auc_score(new_actual_class, new_pred_class, average = average)
        roc_auc_dict[per_class] = roc_auc
    
    
    check = pd.DataFrame(roc_auc_dict.items())
    return mean(check)

def svm_fun_kernel(X_train,y_train,X_test,y_test,kernel_mat):
    import time
    
    start = timeit.default_timer()
    

#     clf = svm.SVC()
    clf = svm.SVC(kernel=kernel_mat)
    
    #Train the model using the training sets
    clf.fit(kernel_mat, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    stop = timeit.default_timer()
    time_final = stop - start
    print("SVM Kernel Time : ", time_final)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Kernel Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,macro_roc_auc_ovo[1],time_final]
    return(check)
    
# In[5]
##########################  SVM Classifier  ################################
def svm_fun(X_train,y_train,X_test,y_test):
    import time
    
    start = timeit.default_timer()
    
    #Create a svm Classifier
    clf = svm.SVC(kernel='linear') # Linear Kernel

    #Train the model using the training sets
    clf.fit(X_train, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    stop = timeit.default_timer()
    time_final = stop - start
    print("SVM Time : ", time_final)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,macro_roc_auc_ovo[1],time_final]
    return(check)
    


# In[5]
##########################  NB Classifier  ################################
def gaus_nb_fun(X_train,y_train,X_test,y_test):
    import time
    
    start = timeit.default_timer()
    
    gnb = GaussianNB()
    y_pred = gnb.fit(X_train, y_train).predict(X_test)
    
    stop = timeit.default_timer()
    time_final = stop - start
    print("NB Time : ", time_final)


    NB_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Gaussian NB Accuracy:",NB_acc)

    NB_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Precision:",NB_prec)
    
    NB_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Recall:",NB_recall)
    
    NB_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB F1 weighted:",NB_f1_weighted)
    
    NB_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Gaussian NB F1 macro:",NB_f1_macro)
    
    NB_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Gaussian NB F1 micro:",NB_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix NB : \n", confuse)
    print("NB Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    check = [NB_acc,NB_prec,NB_recall,NB_f1_weighted,NB_f1_macro,macro_roc_auc_ovo[1],time_final]
    return(check)

# In[5]
##########################  MLP Classifier  ################################
def mlp_fun(X_train,y_train,X_test,y_test):
    import time
    
    start = timeit.default_timer()
    
    # Feature scaling
    scaler = StandardScaler()  
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)  
    X_test_2 = scaler.transform(X_test)


    # Finally for the MLP- Multilayer Perceptron
    mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
    mlp.fit(X_train, y_train)


    y_pred = mlp.predict(X_test_2)
    
    stop = timeit.default_timer()
    time_final = stop - start
    print("MLP Time : ", time_final)
    
    MLP_acc = metrics.accuracy_score(y_test, y_pred)
#     print("MLP Accuracy:",MLP_acc)
    
    MLP_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("MLP Precision:",MLP_prec)
    
    MLP_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("MLP Recall:",MLP_recall)
    
    MLP_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("MLP F1:",MLP_f1_weighted)
    
    MLP_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("MLP F1:",MLP_f1_macro)
    
    MLP_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("MLP F1:",MLP_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix MLP : \n", confuse)
    print("MLP Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [MLP_acc,MLP_prec,MLP_recall,MLP_f1_weighted,MLP_f1_macro,macro_roc_auc_ovo[1],time_final]
    return(check)

# In[5]
##########################  knn Classifier  ################################
def knn_fun(X_train,y_train,X_test,y_test):
    import time
    
    start = timeit.default_timer()
    
    classifier = KNeighborsClassifier(n_neighbors=5)
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)
    
    stop = timeit.default_timer()
    time_final = stop - start
    print("knn Time : ", time_final)

    knn_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Knn Accuracy:",knn_acc)
    
    knn_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Knn Precision:",knn_prec)
    
    knn_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Knn Recall:",knn_recall)
    
    knn_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Knn F1 weighted:",knn_f1_weighted)
    
    knn_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Knn F1 macro:",knn_f1_macro)
    
    knn_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Knn F1 micro:",knn_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix KNN : \n", confuse)
    print("KNN Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [knn_acc,knn_prec,knn_recall,knn_f1_weighted,knn_f1_macro,macro_roc_auc_ovo[1],time_final]
    return(check)

# In[5]
##########################  Random Forest Classifier  ################################
def rf_fun(X_train,y_train,X_test,y_test):
    import time
    
    start = timeit.default_timer()
    
    # Import the model we are using
    from sklearn.ensemble import RandomForestClassifier
    # Instantiate model with 1000 decision trees
    rf = RandomForestClassifier(n_estimators = 100)
    # Train the model on training data
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    
    stop = timeit.default_timer()
    time_final = stop - start
    print("RF Time : ", time_final)

    fr_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Random Forest Accuracy:",fr_acc)
    
    fr_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Random Forest Precision:",fr_prec)
    
    fr_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Random Forest Recall:",fr_recall)
    
    fr_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Random Forest F1 weighted:",fr_f1_weighted)
    
    fr_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Random Forest F1 macro:",fr_f1_macro)
    
    fr_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Random Forest F1 micro:",fr_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix RF : \n", confuse)
    print("RF Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [fr_acc,fr_prec,fr_recall,fr_f1_weighted,fr_f1_macro,macro_roc_auc_ovo[1],time_final]
    return(check)

# In[5]
    ##########################  Logistic Regression Classifier  ################################
def lr_fun(X_train,y_train,X_test,y_test):
    import time
    
    start = timeit.default_timer()

    model = LogisticRegression(solver='liblinear', random_state=0)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    stop = timeit.default_timer()
    time_final = stop - start
    print("LR Time : ", time_final)

    LR_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix LR : \n", confuse)
    print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,macro_roc_auc_ovo[1],time_final]
    return(check)


def fun_decision_tree(X_train,y_train,X_test,y_test):
    from sklearn import tree
    import time
    
    start = timeit.default_timer()


    
    clf = tree.DecisionTreeClassifier()    
    clf = clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    stop = timeit.default_timer()
    time_final = stop - start
    print("DT Time : ", time_final) 
    
    dt_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    dt_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    dt_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    dt_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    dt_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    dt_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix DT : \n", confuse)
    print("DT Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [dt_acc,dt_prec,dt_recall,dt_f1_weighted,dt_f1_macro,macro_roc_auc_ovo[1],time_final]
    return(check)


In [34]:

freq_vec = np.load("E:/RA/Adversarial Attack/PacBio Dataset/Feature_Vectors/PSSM2Vec_illumina_10000_red_seq_8220.npy",allow_pickle=True)

# final_feature_vector = np.load("E:/RA/Adversarial Attack/PacBio Dataset/NovaSeq_error_files/Min2Vec_illumina_5000_red_seq_8220.npy",allow_pickle=True)
attributes = np.load("E:/RA/Adversarial Attack/Dataset/Reduced_preprocessed/variant_names_8220.npy",allow_pickle=True)

In [35]:
unique_hst = list(np.unique(attributes))

int_hosts = []
for ind_unique in range(len(attributes)):
    variant_tmp = attributes[ind_unique]
    ind_tmp = unique_hst.index(variant_tmp)
    int_hosts.append(ind_tmp)

In [36]:
X = np.array(freq_vec)
y = np.array(int_hosts)

In [39]:
import timeit


svm_table = []
gauu_nb_table = []
mlp_table = []
knn_table = []
rf_table = []
lr_table = []
dt_table = []

total_splits = 5
from sklearn.model_selection import ShuffleSplit # or StratifiedShuffleSplit
sss = ShuffleSplit(n_splits=total_splits, test_size=0.3)

for w in range(total_splits):

    sss.get_n_splits(X, y)
    train_index, test_index = next(sss.split(X, y)) 

    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    start = timeit.default_timer()
    gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
    stop = timeit.default_timer()
    print("NB Time : ", stop - start) 

    start = timeit.default_timer()
    mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
    stop = timeit.default_timer()
    print("MLP Time : ", stop - start) 

    start = timeit.default_timer()
    knn_return = knn_fun(X_train,y_train,X_test,y_test)
    stop = timeit.default_timer()
    print("KNN Time : ", stop - start) 

    start = timeit.default_timer()
    rf_return = rf_fun(X_train,y_train,X_test,y_test)
    stop = timeit.default_timer()
    print("RF Time : ", stop - start) 

    start = timeit.default_timer()
    lr_return = lr_fun(X_train,y_train,X_test,y_test)
    stop = timeit.default_timer()
    print("LR Time : ", stop - start) 

    start = timeit.default_timer()
    dt_return = fun_decision_tree(X_train,y_train,X_test,y_test)
    stop = timeit.default_timer()
    print("DT Time : ", stop - start) 

    start = timeit.default_timer()
    svm_return = svm_fun(X_train,y_train,X_test,y_test)
    stop = timeit.default_timer()
    print("SVM Time : ", stop - start) 

    gauu_nb_table.append(gauu_nb_return)
    mlp_table.append(mlp_return)
    knn_table.append(knn_return)
    rf_table.append(rf_return)
    lr_table.append(lr_return)
    dt_table.append(dt_return)
    svm_table.append(svm_return)

svm_table_final = DataFrame(svm_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
gauu_nb_table_final = DataFrame(gauu_nb_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
mlp_table_final = DataFrame(mlp_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
knn_table_final = DataFrame(knn_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
rf_table_final = DataFrame(rf_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lr_table_final = DataFrame(lr_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

dt_table_final = DataFrame(dt_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])




NB Time :  0.2647252999995544
Confusion Matrix NB : 
 [[ 0  0  0 ...  1  0  7]
 [ 0  0  0 ...  1  0  4]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  2]
 [ 0  0  0 ...  0  0 23]]
NB Class Wise Accuracy :  [0.         0.         0.         0.         0.         0.
 0.33333333 0.17391304 0.         0.         0.         0.09090909
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 1.         0.         0.         0.         0.         0.
 0.         0.625      0.         0.         0.         0.28571429
 0.         0.         0.         0.         0.76666667]
NB Time :  0.42733510000107344


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


MLP Time :  8.560121499998786
Confusion Matrix MLP : 
 [[ 64  75   0 ...   0   0   3]
 [ 47 469   0 ...   0   1   1]
 [  0   5   0 ...   0   0   0]
 ...
 [  2   3   0 ...   0   0   0]
 [  8  36   0 ...   0   0   1]
 [  0   5   0 ...   0   0  21]]
MLP Class Wise Accuracy :  [0.31219512 0.67191977 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.1657754  0.1682243  0.         0.         0.         0.
 0.5        0.33333333 0.         0.         0.         0.
 0.52068127 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.7       ]


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


MLP Time :  8.7947505000011
knn Time :  0.5971175999984553
Confusion Matrix KNN : 
 [[ 72  61   0 ...   0   0   2]
 [ 96 370   0 ...   0   2   0]
 [  0   4   0 ...   0   0   0]
 ...
 [  3   2   0 ...   0   0   0]
 [  9  27   0 ...   0   2   0]
 [  1   3   0 ...   0   1  23]]
KNN Class Wise Accuracy :  [0.35121951 0.53008596 0.         0.         0.         0.
 0.         0.2173913  0.         0.02061856 0.04       0.09090909
 0.         0.         0.         0.         0.33333333 0.06060606
 0.22459893 0.1588785  0.13333333 0.02870813 0.         0.
 0.         0.33333333 0.         0.         0.         0.
 0.32360097 0.         0.         0.         0.         0.28571429
 0.         0.         0.         0.03636364 0.76666667]


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


KNN Time :  0.8233559000000241
RF Time :  1.2421403999996983
Confusion Matrix RF : 
 [[ 32  75   0 ...   2   1   2]
 [ 33 435   0 ...   0   2   0]
 [  1   4   0 ...   0   0   0]
 ...
 [  0   3   0 ...   2   0   0]
 [  4  29   0 ...   0   4   0]
 [  2   2   0 ...   0   1  22]]
RF Class Wise Accuracy :  [0.15609756 0.62320917 0.         0.         0.         0.
 0.         0.17391304 0.         0.         0.04       0.09090909
 0.         0.25       0.         0.         0.         0.
 0.26737968 0.20560748 0.13333333 0.08133971 0.         0.
 0.5        0.33333333 0.01298701 0.         0.         0.04545455
 0.50364964 0.         0.         0.         0.         0.21428571
 0.         0.         0.33333333 0.07272727 0.73333333]


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


RF Time :  1.4798559000009845
LR Time :  3.2106364000010217
Confusion Matrix LR : 
 [[  0 205   0 ...   0   0   0]
 [  0 698   0 ...   0   0   0]
 [  0   6   0 ...   0   0   0]
 ...
 [  0   6   0 ...   0   0   0]
 [  0  55   0 ...   0   0   0]
 [  0  30   0 ...   0   0   0]]
LR Class Wise Accuracy :  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


LR Time :  3.4265181999999186
DT Time :  0.14825679999921704
Confusion Matrix DT : 
 [[ 44  76   0 ...   0   0   3]
 [ 44 452   0 ...   0   0   0]
 [  1   4   0 ...   0   0   0]
 ...
 [  2   3   0 ...   0   0   0]
 [  6  31   1 ...   0   2   0]
 [  3   2   0 ...   0   1  19]]
DT Class Wise Accuracy :  [0.21463415 0.64756447 0.         0.         0.         0.
 0.         0.17391304 0.         0.02061856 0.08       0.09090909
 0.         0.         0.         0.         0.         0.
 0.22459893 0.17757009 0.13333333 0.06698565 0.         0.
 0.5        0.33333333 0.         0.         0.         0.04545455
 0.46715328 0.         0.         0.         0.         0.21428571
 0.         0.         0.         0.03636364 0.63333333]


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


DT Time :  0.5319851999993261
SVM Time :  9.641700600001059
Confusion Matrix SVM : 
 [[  0 205   0 ...   0   0   0]
 [  0 698   0 ...   0   0   0]
 [  0   6   0 ...   0   0   0]
 ...
 [  0   6   0 ...   0   0   0]
 [  0  55   0 ...   0   0   0]
 [  0  30   0 ...   0   0   0]]
SVM Class Wise Accuracy :  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM Time :  9.905902099999366


In [40]:
#taking average of all k-fold performance values
final_mean_mat = []

final_mean_mat.append(np.transpose((list(svm_table_final.mean()))))
final_mean_mat.append(np.transpose((list(gauu_nb_table_final.mean()))))
final_mean_mat.append(np.transpose((list(mlp_table_final.mean()))))
final_mean_mat.append(np.transpose((list(knn_table_final.mean()))))
final_mean_mat.append(np.transpose((list(rf_table_final.mean()))))
final_mean_mat.append(np.transpose((list(lr_table_final.mean()))))
final_mean_mat.append(np.transpose((list(dt_table_final.mean()))))

final_avg_mat = DataFrame(final_mean_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","ROC AUC","Runtime (Sec.)"], 
                          index=["SVM","NB","MLP","KNN","RF","LR","DT"])

final_avg_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)   ROC AUC  \
SVM  0.283049   0.080117  0.283049       0.124885    0.010761  0.500000   
NB   0.017032   0.006886  0.017032       0.008739    0.021586  0.527918   
MLP  0.332117   0.225336  0.332117       0.257017    0.068981  0.530755   
KNN  0.278589   0.235603  0.278589       0.242032    0.097405  0.537256   
RF   0.328062   0.271684  0.328062       0.276695    0.112399  0.547944   
LR   0.283049   0.080117  0.283049       0.124885    0.010761  0.500000   
DT   0.325629   0.269546  0.325629       0.273009    0.097713  0.539174   

     Runtime (Sec.)  
SVM        9.641701  
NB         0.264725  
MLP        8.560121  
KNN        0.597118  
RF         1.242140  
LR         3.210636  
DT         0.148257